import java.awt.Color;
import java.util.ArrayList;
import javax.swing.table.DefaultTableModel;


public class telaProdutos extends javax.swing.JFrame {

      ConexaoComputador cc = new ConexaoComputador();
      ArrayList<Produto> lista = cc.consultarProdutos();

    /**
     * Creates new form telaProdutos
     */
    public telaProdutos() {
       initComponents();
       setLocationRelativeTo(null);
        lista = cc.consultarProdutos();
        System.out.println(lista.get(1).getDesc());
        DefaultTableModel model = (DefaultTableModel) tablePro.getModel();
      for( int i = 0; i < lista.size(); i++){
          model.addRow(new Object []{lista.get(i).getCodigo(), lista.get(i).getNome(), lista.get(i).getQuantidade(), lista.get(i).getDesc(), lista.get(i).getPreco()});
      }
      }
       
      

    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        labelProd = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablePro = new javax.swing.JTable();
        AddBtn = new javax.swing.JButton();
        EditBtn = new javax.swing.JButton();
        ExcBtn = new javax.swing.JButton();
        BtnVoltar1 = new javax.swing.JButton();
        ExcBtn1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        labelProd.setBackground(new java.awt.Color(255, 0, 255));
        labelProd.setFont(new java.awt.Font("Nirmala UI Semilight", 1, 18)); // NOI18N
        labelProd.setForeground(new java.awt.Color(204, 102, 255));
        labelProd.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgPC.png"))); // NOI18N
        labelProd.setText("PRODUTOS");
        labelProd.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(153, 204, 255), new java.awt.Color(204, 153, 255), new java.awt.Color(153, 204, 255), new java.awt.Color(204, 153, 255)));

        tablePro.setBackground(new java.awt.Color(204, 255, 255));
        tablePro.setForeground(new java.awt.Color(51, 51, 51));
        tablePro.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Código", "Nome", "Quantidade", "Descrição", "Preço"
            }
        ));
        jScrollPane1.setViewportView(tablePro);

        AddBtn.setFont(new java.awt.Font("Nirmala UI Semilight", 0, 14)); // NOI18N
        AddBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgAdd.png"))); // NOI18N
        AddBtn.setText("Adicionar");
        AddBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddBtnActionPerformed(evt);
            }
        });

        EditBtn.setFont(new java.awt.Font("Nirmala UI Semilight", 0, 14)); // NOI18N
        EditBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgEditar.png"))); // NOI18N
        EditBtn.setText("Editar");
        EditBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EditBtnActionPerformed(evt);
            }
        });

        ExcBtn.setFont(new java.awt.Font("Nirmala UI Semilight", 0, 14)); // NOI18N
        ExcBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgExcluir.png"))); // NOI18N
        ExcBtn.setText("Excluir");
        ExcBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ExcBtnActionPerformed(evt);
            }
        });

        BtnVoltar1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgtelaClienteHouse.png"))); // NOI18N
        BtnVoltar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnVoltar1ActionPerformed(evt);
            }
        });

        ExcBtn1.setFont(new java.awt.Font("Nirmala UI Semilight", 0, 14)); // NOI18N
        ExcBtn1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Reload-32x.png"))); // NOI18N
        ExcBtn1.setText("Atualizar");
        ExcBtn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ExcBtn1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(labelProd, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(96, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 599, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(91, 91, 91)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(AddBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(EditBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(ExcBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(ExcBtn1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(95, 95, 95))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(BtnVoltar1)
                        .addContainerGap())))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(labelProd)
                        .addGap(83, 83, 83)
                        .addComponent(AddBtn)
                        .addGap(45, 45, 45)
                        .addComponent(EditBtn)
                        .addGap(43, 43, 43)
                        .addComponent(ExcBtn)
                        .addGap(49, 49, 49)
                        .addComponent(ExcBtn1))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(104, 104, 104)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 155, Short.MAX_VALUE)
                .addComponent(BtnVoltar1)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 48, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void AddBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddBtnActionPerformed

        telaAddProduto add = new telaAddProduto();
        add.setVisible(true);
        

    }//GEN-LAST:event_AddBtnActionPerformed

    private void BtnVoltar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnVoltar1ActionPerformed

        telaPrincipal tela = new telaPrincipal();
        tela.setVisible(true);
        dispose();
    }//GEN-LAST:event_BtnVoltar1ActionPerformed

    private void ExcBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ExcBtnActionPerformed
        int selectedIndex = tablePro.getSelectedRow();
        ((DefaultTableModel)tablePro.getModel()).removeRow(selectedIndex);
        int id = lista.get(selectedIndex).getCodigo();
        cc.excluirProdutos(id);

        

        // TODO add your handling code here:
    }//GEN-LAST:event_ExcBtnActionPerformed

    private void EditBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EditBtnActionPerformed
        telaAltProduto add = new telaAltProduto();
        int selectedIndex = tablePro.getSelectedRow();
        String nome = lista.get(selectedIndex).getNome(); 
        String desc = lista.get(selectedIndex).getDesc(); 
        float preco = lista.get(selectedIndex).getPreco(); 
        int quant = lista.get(selectedIndex).getQuantidade(); 
        int id = lista.get(selectedIndex).getCodigo();
        add.setTxtDesc(desc);
        add.setTxtNome(nome);
        add.setTxtPreco(preco);
        add.setTxtQuant(quant);
        add.setId(id);
        add.setVisible(true);

        // TODO add your handling code here:
    }//GEN-LAST:event_EditBtnActionPerformed

    private void ExcBtn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ExcBtn1ActionPerformed
        lista = cc.consultarProdutos();
        DefaultTableModel model = (DefaultTableModel) tablePro.getModel();
        model.setRowCount(0);
      for( int k = 0; k < lista.size(); k++){
          model.addRow(new Object []{lista.get(k).getCodigo(), lista.get(k).getNome(), lista.get(k).getQuantidade(), lista.get(k).getDesc(), lista.get(k).getPreco()});
          System.out.println(k);
      }    }//GEN-LAST:event_ExcBtn1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(telaProdutos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(telaProdutos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(telaProdutos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(telaProdutos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new telaProdutos().setVisible(true);
                
            }
        });
        
        /*labelProd label = new labelProd();
        labelProd.setOpaque(false);
        label.setBackground(Color.blue);*/
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AddBtn;
    private javax.swing.JButton BtnVoltar1;
    private javax.swing.JButton EditBtn;
    private javax.swing.JButton ExcBtn;
    private javax.swing.JButton ExcBtn1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel labelProd;
    private javax.swing.JTable tablePro;
    // End of variables declaration//GEN-END:variables
}
